# Generated by Django 3.0 on 2020-11-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201117_2215'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='ans_given',
            field=models.ManyToManyField(blank=True, to='main.Answer'),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='ques_asked',
            field=models.ManyToManyField(blank=True, to='main.Questions'),
        ),
    ]
