# Generated by Django 3.1.3 on 2020-11-16 06:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stackoverflowuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='stackoverflowuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='stackoverflowuser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='stackoverflowuser',
            name='staff',
        ),
    ]
