# Generated by Django 3.0 on 2020-11-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201118_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pic'),
        ),
    ]
