# Generated by Django 3.1.1 on 2020-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201118_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='user_profile_pic'),
        ),
    ]
