# Generated by Django 3.0 on 2020-11-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20201118_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
