# Generated by Django 3.0 on 2020-11-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201117_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='has_accepted_answer',
            field=models.BooleanField(default=False),
        ),
    ]
