# Generated by Django 3.1.3 on 2020-11-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201117_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
