# Generated by Django 3.1.1 on 2020-11-17 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201117_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_toans',
            new_name='question_to_ans',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='views',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='main.Answer'),
        ),
        migrations.AddField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
