# Generated by Django 3.1.1 on 2020-11-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201117_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
